.TH LIBRND 7 DATE "librnd-VERSION"
.SH NAME
librnd \- a general-purpose data structure library in pure ANSI C
.SH DESCRIPTION
.P
.B librnd
is a general-purpose library implementing common data structures for programming
purposes. The library should be as flexible as reasonably possible, while
remaining very intuitive to the user.
.P
Documentation is scattered in form of man pages, please refer to those when in
need, but generally speaking, for a person well versed in C, there should be no
big surprises.
.SS Supported Data Structures \fR(as of VERSION)\fP
.IP \(bu
stack
.sp -1
.IP \(bu
queue
.SS Generic Data vs. Primitive Types
.P
Every major function for inserting, removing, getting and setting elements is
available in 2 forms:
.IP \(bu
.B Generic Form
- for any data hidden behind a
.BR void* .
.sp -1
.IP \(bu
.B Suffixed Form
- for primitive types only.
.TP
.IR Examples :
.IP \(bu
.BR rnd_stack_push (3)
\h'2n'- reads from a \fBvoid*\fP, generic
.sp -1
.IP \(bu
.BR rnd_stack_pushi (3)
\h'1n'- pass-by-value \fBint\fP, suffixed
.sp -1
.IP \(bu
.BR rnd_stack_pushus (3)
- pass-by-value \fBunsigned short\fP, suffixed
.P
This design ensures that it is possible to store any kind of data in any data
structure (using Generic Form functions), but for simple primitives there exist
separate functions that allow using pass-by-value, which is often more
convenient.
.P
Here is a full table of suffixes, although all you need to remember is to use
the first letters of your target type:
.TS
box;
rb|lb
r |l
rb|lb.
SUFFIX	TYPE
_
none 	any (\fBvoid*\fP)
l 	long
ul 	unsigned long
i 	int
ui 	unsigned int
s 	short
us 	unsigned short
c 	char
sc 	signed char
uc 	unsigned char
f 	float
d 	double
ld 	long double
.TE
.P
.B "signed char"
is the only explicitly signed type available due to the fact that
.B char
signedness is not defined by the standard.
.SS Thread Safety
.P
.B librnd
was not tested for thread safety and there have been no serious attempts at
ensuring correct execution in a multi-threaded environment.
.P
That said, the library does not rely on global variables, and all functions that
operate on structures are practically self-contained, so it could be sufficient
to simply lock a structure with a mutex before passing it to a function.
.SS Debug Mode
To enable debug mode, recompile the library with
.B RND_DEBUG
defined (default: off).
.P
Debug mode enables additional error checking, which causes some functions to
return more error codes.
.P
When debug mode is disabled, only the vital errors are checked, such as memory
allocations and integer overflows. To find out which errors are checked with and
without debug mode for a particular function, refer to its man page.
.SS Quiet Mode
To enable quiet mode, recompile the library with
.B RND_QUIET
defined (default: off).
.P
Quiet mode suppresses all debug output. By default, all functions aside from
returning error codes also print short error messages and warnings.
.SS Abort Mode
To enable abort mode, recompile the library with
.B RND_ABORT
defined (default: off).
.P
When abort mode is enabled, every caught warning and error will call
.BR exit (1)
after having printed the error message (unless
.B RND_QUIET
was defined).
This functionality is useful for writing simple programs that shouldn't need to
bother with error checking.
.SH CONFORMING TO
The entirety of
.B librnd
is written in pure
.BR C89
for maximum portability. There are no external dependencies besides the C
Standard
Library.
.SH NOTES
.P
In the future, the following additions are planned for the library (order is
arbitrary):
.IP
deque, bitarray, hashmap, linked list, 2D Matrix, 3D Matrix, priority queue, avl
tree, rbtree
.SH BUGS
.P
Please report bugs to the author of the library, either by email or by opening
an issue on GitHub.
.SH AUTHORS
.P
.ad l
.B librnd
was written by
.MT randoragongamedev@gmail.com
Randoragon
.ME .
.br
The source code is available on
.UR https://github.com/randoragon/librnd
GitHub
.UE .
.ad
.SH SEE ALSO
.ad l
.BR rnd_stack (7) ,
.BR rnd_queue (7)
