.TH RND_foo 3 DATE "librnd-VERSION"
.SH NAME
foo - ##
.SH SYNOPSIS
.ad l
#include <rnd.h>
.sp
##
.BR foo(##
.IR ## )
.ad
.SH DESCRIPTION
.P
The
.B foo
function
##
.SH RETURN VALUE
.P
If successful, the
.B foo()
function shall return ##. Otherwise, it shall
return ##
.SH ERRORS
The
.B foo()
function shall fail if:
.IP (1) 1.5i
##
.SH CONFORMING TO
See librnd(3).
.SH SEE ALSO
librnd(3), rnd_stack_create(3), rnd_stack_destroy(3), rnd_stack_clear(3),
rnd_stack_copy(3), rnd_stack_map(3), rnd_stack_push(3), rnd_stack_insert(3),
rnd_stack_quickinsert(3), rnd_stack_peek(3), rnd_stack_pop(3),
rnd_stack_remove(3), rnd_stack_quickremove(3), rnd_stack_get(3),
rnd_stack_set(3), rnd_stack_print(3)
