.TH RND_STACK_QREMOVE 3 DATE "librnd-VERSION"
.SH NAME
rnd_stack_qremove, rnd_stack_qremovec, rnd_stack_qremoves,
rnd_stack_qremovei, rnd_stack_qremovel, rnd_stack_qremovesc,
rnd_stack_qremoveuc, rnd_stack_qremoveus, rnd_stack_qremoveui,
rnd_stack_qremoveul, rnd_stack_qremovef, rnd_stack_qremoved,
rnd_stack_qremoveld \- quickly remove an element from any position of a stack
.SH SYNOPSIS
.ad l
#include <rnd.h>
.sp
int
.BR rnd_stack_qremove "(struct rnd_stack"
.RI * stack ,
size_t
.IR idx ,
void
.RI * output )
.br
char
.BR rnd_stack_qremovec "(struct rnd_stack"
.RI * stack ,
size_t
.IR idx )
.br
short
.BR rnd_stack_qremoves "(struct rnd_stack"
.RI * stack ,
size_t
.IR idx )
.br
int
.BR rnd_stack_qremovei "(struct rnd_stack"
.RI * stack ,
size_t
.IR idx )
.br
long
.BR rnd_stack_qremovel "(struct rnd_stack"
.RI * stack ,
size_t
.IR idx )
.br
signed char
.BR rnd_stack_qremovesc "(struct rnd_stack"
.RI * stack ,
size_t
.IR idx )
.br
unsigned char
.BR rnd_stack_qremoveuc "(struct rnd_stack"
.RI * stack ,
size_t
.IR idx )
.br
unsigned short
.BR rnd_stack_qremoveus "(struct rnd_stack"
.RI * stack ,
size_t
.IR idx )
.br
unsigned int
.BR rnd_stack_qremoveui "(struct rnd_stack"
.RI * stack ,
size_t
.IR idx )
.br
unsigned long
.BR rnd_stack_qremoveul "(struct rnd_stack"
.RI * stack ,
size_t
.IR idx )
.br
float
.BR rnd_stack_qremovef "(struct rnd_stack"
.RI * stack ,
size_t
.IR idx )
.br
double
.BR rnd_stack_qremoved "(struct rnd_stack"
.RI * stack ,
size_t
.IR idx )
.br
long double
.BR rnd_stack_qremoveld "(struct rnd_stack"
.RI * stack ,
size_t
.IR idx )
.sp
Link with \fI-lrnd\fP.
.ad
.SH DESCRIPTION
See
.BR rnd_stack_remove (3).
.P
The functions in the
.BR rnd_stack_qremove ()
family operate in constant time, which is achievable by changing the order of
the elements during removal.
.SH EXAMPLES
To explain how the
.BR rnd_stack_remove ()
and
.BR rnd_stack_qremove ()
families differ, consider the following initial stack (elements listed
from bottom to top):
.IP
.B 1 2 3 4 _ _ _
.P
Now, let us investigate what happens when we try to remove the number
.BR 2 .
.P
The functions in the
.BR rnd_stack_remove ()
family would remove the element, and then move
.BR 3 " and " 4
downwards into the freed spot, without affecting the order:
.IP (1)
.B 1 _ 3 4 _ _ _
.br
\h'2n'^
.IP (2)
.B 1 3 4 _ _ _ _
.br
\h'2n'^ ^
.P
On the contrary, the functions in the
.BR rnd_stack_qremove ()
family achieve the goal faster by moving the top of the stack (in this case
.BR 4 )
into the value that should be removed:
.IP (1)
.B 1 _ 3 4 _ _ _
.br
\h'2n'^
.IP (2)
.B 1 4 3 _ _ _ _
.br
\h'2n'^
.P
The second approach guarantees constant time, but does not preserve the order of
the elements.
.SH SEE ALSO
.ad l
.BR librnd (7),
.BR rnd_stack (7),
.BR rnd_stack_create (3),
.BR rnd_stack_destroy (3),
.BR rnd_stack_clear (3),
.BR rnd_stack_copy (3),
.BR rnd_stack_foreach (3),
.BR rnd_stack_push (3),
.BR rnd_stack_insert (3),
.BR rnd_stack_qinsert (3),
.BR rnd_stack_peek (3),
.BR rnd_stack_pop (3),
.BR rnd_stack_remove (3),
.BR rnd_stack_get (3),
.BR rnd_stack_set (3),
.BR rnd_stack_print (3)

