.\"  Staple - A general-purpose data structure library in pure C89.
.\"  Copyright (C) 2021  Randoragon
.\"
.\"  This library is free software; you can redistribute it and/or
.\"  modify it under the terms of the GNU Lesser General Public
.\"  License as published by the Free Software Foundation;
.\"  version 2.1 of the License.
.\"
.\"  This library is distributed in the hope that it will be useful,
.\"  but WITHOUT ANY WARRANTY; without even the implied warranty of
.\"  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
.\"  Lesser General Public License for more details.
.\"
.\"  You should have received a copy of the GNU Lesser General Public
.\"  License along with this library; if not, write to the Free Software
.\"  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
.\"--------------------------------------------------------------------------------
.TH SP_STACK_INSERT 3 DATE "libstaple-VERSION"
.SH NAME
sp_stack_insert,
sp_stack_insertc,
sp_stack_inserts,
sp_stack_inserti,
sp_stack_insertl,
sp_stack_insertsc,
sp_stack_insertuc,
sp_stack_insertus,
sp_stack_insertui,
sp_stack_insertul,
sp_stack_insertf,
sp_stack_insertd,
sp_stack_insertld,
sp_stack_insertll,
sp_stack_insertull,
sp_stack_insertu8,
sp_stack_insertu16,
sp_stack_insertu32,
sp_stack_insertu64,
sp_stack_inserti8,
sp_stack_inserti16,
sp_stack_inserti32,
sp_stack_inserti64,
sp_stack_insertstr,
sp_stack_insertstrn
\- insert an element at any position of a stack
.SH SYNOPSIS
.ad l
#include <staple.h>
.sp
int
.BR sp_stack_insert "(struct sp_stack"
.RI * stack ,
size_t
.IR idx ,
const void
.RI * elem )
.br
int
.BR sp_stack_insertc "(struct sp_stack"
.RI * stack ,
size_t
.IR idx ,
char
.IR elem )
.br
int
.BR sp_stack_inserts "(struct sp_stack"
.RI * stack ,
size_t
.IR idx ,
short
.IR elem )
.br
int
.BR sp_stack_inserti "(struct sp_stack"
.RI * stack ,
size_t
.IR idx ,
int
.IR elem )
.br
int
.BR sp_stack_insertl "(struct sp_stack"
.RI * stack ,
size_t
.IR idx ,
long
.IR elem )
.br
int
.BR sp_stack_insertsc "(struct sp_stack"
.RI * stack ,
size_t
.IR idx ,
signed char
.IR elem )
.br
int
.BR sp_stack_insertuc "(struct sp_stack"
.RI * stack ,
size_t
.IR idx ,
unsigned char
.IR elem )
.br
int
.BR sp_stack_insertus "(struct sp_stack"
.RI * stack ,
size_t
.IR idx ,
unsigned short
.IR elem )
.br
int
.BR sp_stack_insertui "(struct sp_stack"
.RI * stack ,
size_t
.IR idx ,
unsigned int
.IR elem )
.br
int
.BR sp_stack_insertul "(struct sp_stack"
.RI * stack ,
size_t
.IR idx ,
unsigned long
.IR elem )
.br
int
.BR sp_stack_insertf "(struct sp_stack"
.RI * stack ,
size_t
.IR idx ,
float
.IR elem )
.br
int
.BR sp_stack_insertd "(struct sp_stack"
.RI * stack ,
size_t
.IR idx ,
double
.IR elem )
.br
int
.BR sp_stack_insertld "(struct sp_stack"
.RI * stack ,
size_t
.IR idx ,
long double
.IR elem )
.br
int
.BR sp_stack_insertll "(struct sp_stack"
.RI * stack ,
size_t
.IR idx ,
long long
.IR elem )
.br
int
.BR sp_stack_insertull "(struct sp_stack"
.RI * stack ,
size_t
.IR idx ,
unsigned long long
.IR elem )
.br
int
.BR sp_stack_insertu8 "(struct sp_stack"
.RI * stack ,
size_t
.IR idx ,
uint8_t
.IR elem )
.br
int
.BR sp_stack_insertu16 "(struct sp_stack"
.RI * stack ,
size_t
.IR idx ,
uint16_t
.IR elem )
.br
int
.BR sp_stack_insertu32 "(struct sp_stack"
.RI * stack ,
size_t
.IR idx ,
uint32_t
.IR elem )
.br
int
.BR sp_stack_insertu64 "(struct sp_stack"
.RI * stack ,
size_t
.IR idx ,
uint64_t
.IR elem )
.br
int
.BR sp_stack_inserti8 "(struct sp_stack"
.RI * stack ,
size_t
.IR idx ,
int8_t
.IR elem )
.br
int
.BR sp_stack_inserti16 "(struct sp_stack"
.RI * stack ,
size_t
.IR idx ,
int16_t
.IR elem )
.br
int
.BR sp_stack_inserti32 "(struct sp_stack"
.RI * stack ,
size_t
.IR idx ,
int32_t
.IR elem )
.br
int
.BR sp_stack_inserti64 "(struct sp_stack"
.RI * stack ,
size_t
.IR idx ,
int64_t
.IR elem )
.br
int
.BR sp_stack_insertstr "(struct sp_stack"
.RI * stack ,
size_t
.IR idx ,
const char
.RI * elem )
.br
int
.BR sp_stack_insertstrn "(struct sp_stack"
.RI * stack ,
size_t
.IR idx ,
const char
.RI * elem ,
size_t
.IR len )
.sp
Link with \fI-lstaple\fP.
.ad
.SH DESCRIPTION
The functions in the
.BR sp_stack_insert ()
family are used to insert elements at any position of a stack. The order of
elements above and below the newly inserted element shall be preserved.
.P
.I stack
is the stack that shall be inserted into.
.P
.I idx
is the index at which the new element will be placed. Indices start from 0 and
extend downwards \(em 0 is the top element, 1 is the element below it, and so
on.
.br
Inserting at position \fBn\fP requires \fBn\fP elements to be moved in memory.
Inserting at 0 has the same effect as
.BR sp_stack_push (3).
.br
.I idx
cannot be larger than
.IR stack->size .
.P
.I elem
is the element to be inserted.
.SS Generic Form
.I elem
must be a void pointer to the first byte of the element that shall be inserted.
The number of bytes to copy is equal to
.IR stack->elem_size
field.
.SS Suffixed Form
.I elem
is passed directly in the function argument.
.P
The
.BR sp_stack_insertstr ()
function creates a copy of the string pointed to by
.I elem
and stores the new pointer on the stack. The string must fit in
.I SIZE_MAX
bytes, including the null terminator.
.P
The
.BR sp_stack_insertstrn ()
function is equivalent to
.BR sp_stack_insertstr (),
except it shall always copy exactly
.I len
bytes and append a null terminator at the end.
.I len
must be smaller than
.IR SIZE_MAX .
.SH RETURN VALUE
If successful, the functions in the
.BR sp_stack_insert ()
family shall return 0. Otherwise, they shall return a code indicating the
error.
.SH ERRORS
The functions in the
.BR sp_stack_insert ()
family shall fail if:
.IP \fBSP_EINVAL\fP 1.5i
.I stack
is a null pointer (debug mode only).
.IP \fBSP_EINDEX\fP 1.5i
.I idx
out of range (debug mode only).
.IP \fBSP_ERANGE\fP 1.5i
Maximum buffer size exceeded. See BUGS in
.BR sp_stack (7).
.IP \fBSP_ENOMEM\fP 1.5i
Memory allocation failed.
.SS Generic Form
The
.BR sp_stack_insert ()
function shall fail if:
.IP \fBSP_EINVAL\fP 1.5i
.I elem
is a null pointer (debug mode only).
.SS Suffixed Form
The suffixed
.BR sp_stack_insert ()
functions shall fail if:
.IP \fBSP_EILLEGAL\fP 1.5i
.IR stack->elem_size
does not match the size of the
.I elem
argument (debug mode only).
.P
The
.BR sp_stack_insertstr ()
and
.BR sp_stack_insertstrn ()
functions shall fail if:
.IP \fBSP_EINVAL\fP 1.5i
.I elem
is a null pointer (debug mode only).
.IP \fBSP_ERANGE\fP 1.5i
string too long or
.I len
too large.
.SH CONFORMING TO
See
.BR libstaple (7).
.SH SEE ALSO
.ad l
.BR libstaple (7),
.BR sp_stack (7),
.BR sp_stack_create (3),
.BR sp_stack_destroy (3),
.BR sp_stack_clear (3),
.BR sp_stack_push (3),
.BR sp_stack_peek (3),
.BR sp_stack_pop (3),
.BR sp_stack_remove (3),
.BR sp_stack_qinsert (3),
.BR sp_stack_qremove (3),
.BR sp_stack_get (3),
.BR sp_stack_set (3),
.BR sp_stack_eq (3),
.BR sp_stack_copy (3),
.BR sp_stack_map (3),
.BR sp_stack_print (3)
