on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: 'Build docker image'
        run: docker image build -t staple .
      - name: 'Run docker container'
        run: docker run staple
